# AlphaVantage API Key
ALPHAVANTAGE_API_KEY = "YOUR_ALPHAVANTAGE_API_KEY_HERE"

# News API Key
NEWS_API_KEY = "YOUR_NEWS_API_KEY_HERE"

# Twilio API credentials
TWILIO_ACCOUNT_SID = "YOUR_TWILIO_ACCOUNT_SID_HERE"
TWILIO_AUTH_TOKEN = "YOUR_TWILIO_AUTH_TOKEN_HERE"

# Phone Numbers for Twilio Alerts
FROM_PHONE_NUMBER = "TWILIO_PHONE_NUMBER"  # Twilio phone number
TO_PHONE_NUMBER = "RECIPIENT_PHONE_NUMBER"  # Recipient's phone number
